### ISSUE TITLE
Not compatible with pytest 7.0.1

### ISSUE THREAD

**Issue by automonkey** [brunns/brunns-matchers#14]
When installing deps get error:
`brunns-matchers 2.5.0 has requirement pytest<7.0,>=3.0, but you have pytest 7.0.1.`

Looks like there's already been [a commit that would fix this](https://github.com/brunns/brunns-matchers/commit/ee47400240b9499d287fa3df30b4dc7351c9c21f) and it just needs to be released.

**Comment by brunns** [comment]
That commit still restricts to 6.x - I'll try and get to this soon, though. I want to go with something like `pytest>=x.0`, removing upper bounds completely, as per [Should You Use Upper Bound Version Constraints?](https://iscinumpy.dev/post/bound-version-constraints/), and I'd like to work out what the least restrictive lower bound needs to be.

**Comment by brunns** [comment]
2.5.1 released.

**Comment by automonkey** [comment]
> That commit still restricts to 6.x

Only in the tox testenv though, right? In my codebase pulling in brunns-matchers as a dependency I would have been fine to use pytest 7.0.1?

In any case - thanks for the update!
